# SD212: Graph mining

# Sparse matrices

The objective of this lab is to learn to work with sparse matrices.

In [166]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [167]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [168]:
X_dense

array([[0, 0, 1, 0, 1],
       [0, 1, 0, 0, 2],
       [2, 2, 2, 2, 2],
       [0, 2, 2, 1, 0],
       [2, 0, 0, 0, 2],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 0, 2],
       [1, 0, 2, 1, 2],
       [2, 0, 2, 2, 0],
       [1, 1, 2, 2, 0]])

In [169]:
X_csr = sparse.csr_matrix(X_dense)

In [170]:
X_csr.shape

(10, 5)

In [171]:
X_csr.nnz

31

The data structure consists of 3 vectors:

In [172]:
X_csr.indices

array([2, 4, 1, 4, 0, 1, 2, 3, 4, 1, 2, 3, 0, 4, 0, 2, 3, 0, 1, 4, 0, 2,
       3, 4, 0, 2, 3, 0, 1, 2, 3], dtype=int32)

In [173]:
X_csr.indptr

array([ 0,  2,  4,  9, 12, 14, 17, 20, 24, 27, 31], dtype=int32)

In [174]:
X_csr.data

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 1, 1, 2, 2])

## To do

Can you find the number of non-zeros ``nnz`` and the shape of the matrix from these vectors?

In [175]:
nnz = X_csr.indptr[-1]
nnz2 = len(X_csr.data)

shape = (len(X_csr.indptr) -1, max(X_csr.indices) + 1)

print("nnz = ", nnz)
print("nnz2 = ", nnz2)
print("shape = ", shape, "\n")

nnz =  31
nnz2 =  31
shape =  (10, 5) 



## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [176]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [177]:
X_dense

array([[0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [178]:
a = np.ones(n_col, dtype=int)

In [179]:
b = X.dot(a)

In [180]:
b

array([2, 1, 3, 1, 2, 2, 2, 2, 2, 2])

In [181]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [182]:
b

array([4, 3, 7, 5])

In [183]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [184]:
A

array([[1, 1],
       [0, 1],
       [0, 1],
       [0, 0]])

In [185]:
B

array([[0, 1],
       [0, 1],
       [0, 2],
       [0, 0],
       [1, 2],
       [1, 2],
       [1, 2],
       [0, 1],
       [0, 1],
       [1, 2]])

In [186]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [187]:
B

<10x2 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [188]:
B.toarray()

array([[0, 1],
       [0, 1],
       [0, 2],
       [0, 0],
       [1, 2],
       [1, 2],
       [1, 2],
       [0, 1],
       [0, 1],
       [1, 2]])

In [189]:
X.T.dot(X)

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Column format>

In [190]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.int64'>'
	with 70 stored elements in Compressed Sparse Row format>

In [191]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [192]:
X

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 31 stored elements in Compressed Sparse Row format>

In [193]:
Y = X > 1

In [194]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 20 stored elements in Compressed Sparse Row format>

In [195]:
Y.dot(np.ones(n_col, dtype=int))

array([0, 1, 2, 4, 2, 2, 2, 2, 2, 3])

In [196]:
Y.dot(np.ones(n_col, dtype=bool))

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [197]:
Z = 2 * X + 5 * Y

In [198]:
Z

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 31 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [199]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

In [200]:
# Computing the vector of the Euclidean norm of each row
norms = np.sqrt(X.multiply(X).sum(axis=1))

norms

matrix([[1.73205081],
        [2.23606798],
        [1.73205081],
        [3.60555128],
        [3.60555128],
        [3.        ],
        [1.41421356],
        [2.23606798],
        [1.41421356],
        [3.46410162],
        [1.73205081],
        [3.16227766],
        [2.        ],
        [2.23606798],
        [3.16227766],
        [3.60555128],
        [2.23606798],
        [2.64575131],
        [4.        ],
        [3.        ]])

## Slicing

Sparse matrices can be sliced like numpy arrays.

In [111]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [112]:
X = sparse.csr_matrix(X_dense)

In [113]:
indices = [2, 5, 6]

In [114]:
X[indices]

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [115]:
X[:, [1, 3]]

<10x2 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

## To do 

Consider the following matrix:

In [204]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

IndexError: index results in >2 dimensions

## DIAG format

In [117]:
D = sparse.diags(np.arange(10))

In [118]:
D

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements (1 diagonals) in DIAgonal format>

In [119]:
D.data

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [120]:
D.nnz

10

In [121]:
D = sparse.csr_matrix(D)

In [122]:
D.data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [123]:
D.nnz

9

In [124]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [125]:
D.dot(X)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [126]:
D = sparse.diags(np.ones(4))

In [127]:
X.dot(D)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 23 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [128]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 

## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [129]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [130]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [131]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in COOrdinate format>

In [132]:
X_coo.row

array([1, 4, 2], dtype=int32)

In [133]:
X_coo.col

array([2, 0, 2], dtype=int32)

In [134]:
X_coo.data

array([1, 2, 3])

You can change the format:

In [135]:
X_csr = X_coo.tocsr()

In [136]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [137]:
X_csr.indices

array([2, 2, 0], dtype=int32)

In [138]:
X_csr.indptr

array([0, 0, 1, 2, 2, 3], dtype=int32)

In [139]:
X_csr.data

array([1, 3, 2])

In [140]:
X_csr.tocoo()

<5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in COOrdinate format>

You can directly load a CSR matrix from COO format:

In [141]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [142]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

Duplicate entries are summed in CSR, not in COO:

In [143]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [144]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [145]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>

In [146]:
X_coo.data

array([1, 2, 3, 4])

In [147]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [148]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [149]:
X_csr.data

array([5, 3, 2])

## To do

* Build the following matrix in sparse CSR format:
$$
\begin{pmatrix}
0 & 0 & 1& 2\\
3 & 0& 0& 0\\
0& 0& 4& 0
\end{pmatrix}
$$